version: 2

checkout:
  post:
    - ./ci-support/checkout_merge_commit.sh
        
aliases:

  - &setup_miniconda
    name: setup_miniconda
    command: |
      mkdir -p workspace
      git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
      python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'
      
  - &create_conda_env
    name: create_conda_env
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -y -q conda
       conda config --set anaconda_upload no
       conda create -n py3 -c cdat/label/nightly -c conda-forge -c cdat genutil nose flake8 "numpy=1.13" "python>3" cdat_info testsrunner
       conda create -n py2 -c cdat/label/nightly -c conda-forge -c cdat genutil nose flake8 "numpy=1.13" "python<3" cdat_info testsrunner

  - &setup_cdutil
    name: setup_cdutil
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export UVCDAT_ANONYMOUS_LOG=False
       source activate py3
       python setup.py install
       source activate py2
       rm -rf build
       python setup.py install

  - &run_cdutil_tests
    name: run_cdutil_tests
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export UVCDAT_ANONYMOUS_LOG=False
       set -e
       source activate py2
       python run_tests.py -v2 -H 
       RESULT=$?
       echo "*** py2 test result: "${RESULT}
       source activate py3
       python run_tests.py -v2 -H
       PY3_RESULT=$?
       echo "*** py3 test result: "${PY3_RESULT}
       RESULT=$(( $RESULT + $PY3_RESULT))
       exit $RESULT

  - &conda_upload
    name: conda_upload
    command: |
       if [[ $CIRCLE_BRANCH != 'revisit_run_tests' ]]; then
          exit 0
       fi
       export PATH=${HOME}/project/$WORKDIR/miniconda/bin:$PATH
       conda install conda-build anaconda-client
       conda config --set anaconda_upload no
       export CONDA_BLD_PATH=`pwd`/conda_build
       git clone git://github.com/cdat/conda-recipes
       cd conda-recipes
       export PKG_NAME=cdutil
       export USER=cdat
       export VERSION=8.0
       export LABEL=unstable
       python ./prep_for_build.py -l $VERSION
       conda build $PKG_NAME -c cdat/label/nightly -c conda-forge -c cdat 
       conda build $PKG_NAME -c cdat/label/nightly -c conda-forge -c cdat --python=3.6
       anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL $CONDA_BLD_PATH/$OS/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

jobs:
  macos_cdutil:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "workspace/test_macos_cdutil"
      OS: "osx-64"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cdutil
      - run: *run_cdutil_tests
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html

  linux_cdutil:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_cdutil"
      OS: "linux-64"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cdutil
      - run: *run_cdutil_tests
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html

workflows:
  version: 2
  cdutil:
    jobs:
      - macos_cdutil
      - linux_cdutil

       