version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &conda_rerender
    name: conda_rerender
    command: |
       git clone -b conda_forge_pinning https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -l $LAST_STABLE -B 0 -p $PKG_NAME -b $CIRCLE_BRANCH --do_rerender

  - &conda_build
    name: conda_build
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --add channels conda-forge --force
       conda config --add channels cdat/label/nightly --force
       conda config --set channel_priority strict
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -p $PKG_NAME --build_version $BUILD_VARIANT_VER --do_build

  - &setup_run_tests
    name: setup_run_tests
    environment:
       PKGS: "genutil numpy cdat_info testsrunner"
       CHANNELS: "-c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda create -y -n $ENV_NAME --use-local $CHANNELS "$CONDA_PY_VER" $PKG_NAME $PKGS $COVERAGE_PKGS
       conda activate $ENV_NAME
       conda list

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       python run_tests.py -H -v2 -n 2 $COVERAGE
       conda deactivate

  - &conda_upload
    name: conda_upload
    command: |
       if [[ $CIRCLE_BRANCH != "master" ]]; then
          exit 0
       fi
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       UPLOAD_OPTIONS="-t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL"
       anaconda $UPLOAD_OPTIONS $WORKDIR/miniconda/conda-bld/noarch/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &run_coveralls
    name: run_coveralls
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       coveralls
       conda deactivate

jobs:
   linux_cdutil:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: "/home/circleci/project/workdir"
         PKG_NAME: "cdutil"
         ENV_NAME: "test_cdutil"
         LAST_STABLE: "8.2"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "noarch"
         COVERAGE: "-c tests/coverage.json --coverage-from-egg"
         COVERAGE_PKGS: "coverage coveralls"
         # for conda_upload
         VERSION: "8.2"
         USER: "cdat"
         LABEL: "nightly"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - run: *run_coveralls
         - run: *conda_upload

workflows:
   version: 2
   cdutil:
      jobs:
         - linux_cdutil
